const QUESTIONS = [
  // ===== Indonesia =====
  { q: 'Ibu kota Indonesia?', a: 'jakarta' },
  { q: 'Presiden pertama Indonesia?', a: 'soekarno' },
  { q: 'Presiden kedua Indonesia?', a: 'soeharto' },
  { q: 'Presiden ketiga Indonesia?', a: 'bj habibie' },
  { q: 'Presiden keempat Indonesia?', a: 'abdurrahman wahid' },
  { q: 'Presiden kelima Indonesia?', a: 'megawati' },
  { q: 'Presiden keenam Indonesia?', a: 'susilo bambang yudhoyono' },
  { q: 'Presiden ketujuh Indonesia?', a: 'joko widodo' },
  { q: 'Proklamasi kemerdekaan Indonesia tahun?', a: '1945' },
  { q: 'Pulau terbesar di Indonesia?', a: 'kalimantan' },
  { q: 'Pulau terpadat di Indonesia?', a: 'jawa' },
  { q: 'Pulau terbesar kedua di Indonesia?', a: 'sumatera' },
  { q: 'Lagu kebangsaan Indonesia?', a: 'indonesia raya' },
  { q: 'Pencipta lagu Indonesia Raya?', a: 'wr supratman' },
  { q: 'Mata uang Indonesia?', a: 'rupiah' },
  { q: 'Bahasa resmi Indonesia?', a: 'indonesia' },
  { q: 'Hari kemerdekaan Indonesia tanggal?', a: '17 agustus' },
  { q: 'Wakil presiden pertama Indonesia?', a: 'mohammad hatta' },
  { q: 'Pahlawan wanita dari Aceh?', a: 'cut nyak dien' },
  { q: 'Pahlawan pria dari Aceh?', a: 'teuku umar' },
  { q: 'Raja terakhir Majapahit?', a: 'hayam wuruk' },
  { q: 'Patih terkenal Majapahit?', a: 'gajah mada' },
  { q: 'Candi Buddha terbesar di Indonesia?', a: 'borobudur' },
  { q: 'Candi Hindu terbesar di Indonesia?', a: 'prambanan' },
  { q: 'Danau terbesar di Indonesia?', a: 'danau toba' },
  { q: 'Pulau dewata?', a: 'bali' },
  { q: 'Komodo berasal dari pulau?', a: 'komodo' },
  { q: 'Suku di Sumatera Utara?', a: 'batak' },
  { q: 'Suku di Sulawesi Selatan?', a: 'bugis' },
  { q: 'Rumah adat Minangkabau?', a: 'gadang' },
  { q: 'Alat musik dari Jawa Barat?', a: 'angklung' },
  { q: 'Tari dari Bali?', a: 'kecak' },
  { q: 'Batik berasal dari?', a: 'jawa' },
  { q: 'Gunung tertinggi di Jawa?', a: 'semeru' },
  { q: 'Selat antara Jawa dan Sumatera?', a: 'sunda' },
  { q: 'Ibu kota provinsi Jawa Barat?', a: 'bandung' },
  { q: 'Ibu kota provinsi Jawa Timur?', a: 'surabaya' },
  { q: 'Ibu kota provinsi Jawa Tengah?', a: 'semarang' },

  // ===== Dunia =====
  { q: 'Ibu kota Jepang?', a: 'tokyo' },
  { q: 'Ibu kota Prancis?', a: 'paris' },
  { q: 'Ibu kota Inggris?', a: 'london' },
  { q: 'Ibu kota Amerika Serikat?', a: 'washington' },
  { q: 'Ibu kota China?', a: 'beijing' },
  { q: 'Ibu kota Korea Selatan?', a: 'seoul' },
  { q: 'Ibu kota Korea Utara?', a: 'pyongyang' },
  { q: 'Ibu kota Thailand?', a: 'bangkok' },
  { q: 'Ibu kota Malaysia?', a: 'kuala lumpur' },
  { q: 'Ibu kota Singapura?', a: 'singapura' },
  { q: 'Ibu kota Australia?', a: 'canberra' },
  { q: 'Ibu kota Jerman?', a: 'berlin' },
  { q: 'Ibu kota Italia?', a: 'roma' },
  { q: 'Ibu kota Spanyol?', a: 'madrid' },
  { q: 'Ibu kota Mesir?', a: 'kairo' },
  { q: 'Ibu kota India?', a: 'new delhi' },
  { q: 'Ibu kota Turki?', a: 'ankara' },
  { q: 'Ibu kota Rusia?', a: 'moskow' },
  { q: 'Ibu kota Arab Saudi?', a: 'riyadh' },
  { q: 'Ibu kota Uni Emirat Arab?', a: 'abu dhabi' },
  { q: 'Ibu kota Vietnam?', a: 'hanoi' },
  { q: 'Ibu kota Filipina?', a: 'manila' },
  { q: 'Ibu kota Belanda?', a: 'amsterdam' },
  { q: 'Ibu kota Portugal?', a: 'lisbon' },
  { q: 'Ibu kota Kanada?', a: 'ottawa' },
  { q: 'Ibu kota Brazil?', a: 'brasilia' },
  { q: 'Ibu kota Argentina?', a: 'buenos aires' },
  { q: 'Ibu kota Meksiko?', a: 'mexico city' },
  { q: 'Ibu kota Pakistan?', a: 'islamabad' },
  { q: 'Ibu kota Iran?', a: 'teheran' },
  { q: 'Ibu kota Irak?', a: 'baghdad' },
  { q: 'Ibu kota Swiss?', a: 'bern' },
  { q: 'Ibu kota Swedia?', a: 'stockholm' },
  { q: 'Ibu kota Norwegia?', a: 'oslo' },
  { q: 'Ibu kota Finlandia?', a: 'helsinki' },
  { q: 'Ibu kota Yunani?', a: 'athena' },
  { q: 'Ibu kota Austria?', a: 'wina' },
  { q: 'Ibu kota Ukraina?', a: 'kyiv' },
  { q: 'Ibu kota Kamboja?', a: 'phnom penh' },
  { q: 'Ibu kota Myanmar?', a: 'naypyidaw' },
  { q: 'Ibu kota Nepal?', a: 'kathmandu' },
  { q: 'Ibu kota Selandia Baru?', a: 'wellington' },
  { q: 'Ibu kota Kenya?', a: 'nairobi' },
  { q: 'Ibu kota Nigeria?', a: 'abuja' },
  { q: 'Ibu kota Afrika Selatan?', a: 'pretoria' },
  { q: 'Benua terbesar di dunia?', a: 'asia' },
  { q: 'Benua terkecil di dunia?', a: 'australia' },
  { q: 'Benua terdingin?', a: 'antartika' },
  { q: 'Samudra terbesar di dunia?', a: 'pasifik' },
  { q: 'Samudra terdalam?', a: 'pasifik' },
  { q: 'Gunung tertinggi di dunia?', a: 'everest' },
  { q: 'Sungai terpanjang di dunia?', a: 'nil' },
  { q: 'Gurun terluas di dunia?', a: 'sahara' },
  { q: 'Negara terluas di dunia?', a: 'rusia' },
  { q: 'Negara dengan penduduk terbanyak?', a: 'india' },
  { q: 'Negara terkecil di dunia?', a: 'vatikan' },
  { q: 'Menara terkenal di Paris?', a: 'eiffel' },
  { q: 'Piramida ada di negara?', a: 'mesir' },
  { q: 'Tembok raksasa ada di negara?', a: 'china' },
  { q: 'Negara kanguru?', a: 'australia' },
  { q: 'Negara sakura?', a: 'jepang' },
  { q: 'Negara gajah putih?', a: 'thailand' },
  { q: 'Negara yang dijuluki Negeri Jiran?', a: 'malaysia' },
  { q: 'Lambang negara Amerika Serikat?', a: 'elang' },
  { q: 'Mata uang Jepang?', a: 'yen' },
  { q: 'Mata uang Amerika Serikat?', a: 'dolar' },
  { q: 'Mata uang Inggris?', a: 'pound' },
  { q: 'Mata uang Malaysia?', a: 'ringgit' },
  { q: 'Mata uang Arab Saudi?', a: 'riyal' },
  { q: 'Mata uang Eropa?', a: 'euro' },

  // ===== Sains =====
  { q: 'Planet terdekat matahari?', a: 'merkurius' },
  { q: 'Planet terjauh dari matahari?', a: 'neptunus' },
  { q: 'Planet merah?', a: 'mars' },
  { q: 'Planet terbesar di tata surya?', a: 'jupiter' },
  { q: 'Planet bercincin indah?', a: 'saturnus' },
  { q: 'Planet terpanas?', a: 'venus' },
  { q: 'Planet tempat kita hidup?', a: 'bumi' },
  { q: 'Satelit alami bumi?', a: 'bulan' },
  { q: 'Bintang pusat tata surya?', a: 'matahari' },
  { q: 'Lambang kimia air?', a: 'h2o' },
  { q: 'Lambang kimia oksigen?', a: 'o' },
  { q: 'Lambang kimia emas?', a: 'au' },
  { q: 'Lambang kimia besi?', a: 'fe' },
  { q: 'Lambang kimia karbon?', a: 'c' },
  { q: 'Lambang kimia natrium?', a: 'na' },
  { q: 'Gas yang kita hirup?', a: 'oksigen' },
  { q: 'Gas yang kita buang?', a: 'karbon dioksida' },
  { q: 'Gas untuk balon terbang?', a: 'helium' },
  { q: 'Bagian terkecil dari makhluk hidup?', a: 'sel' },
  { q: 'Organ pemompa darah?', a: 'jantung' },
  { q: 'Organ untuk berpikir?', a: 'otak' },
  { q: 'Organ untuk bernapas?', a: 'paru paru' },
  { q: 'Organ penyaring darah?', a: 'ginjal' },
  { q: 'Tulang terpanjang di tubuh?', a: 'femur' },
  { q: 'Zat hijau daun?', a: 'klorofil' },
  { q: 'Proses tumbuhan memasak makanan?', a: 'fotosintesis' },
  { q: 'Kecepatan cahaya sekitar ... km/detik?', a: '300000' },
  { q: 'Alat pengukur suhu?', a: 'termometer' },
  { q: 'Alat pengukur gempa?', a: 'seismograf' },
  { q: 'Bagian atom bermuatan positif?', a: 'proton' },
  { q: 'Bagian atom bermuatan negatif?', a: 'elektron' },
  { q: 'Bagian atom netral?', a: 'neutron' },
  { q: 'Pusat tata surya?', a: 'matahari' },
  { q: 'Galaksi tempat kita tinggal?', a: 'bima sakti' },
  { q: 'Ilmu tentang makhluk hidup?', a: 'biologi' },
  { q: 'Ilmu tentang benda langit?', a: 'astronomi' },
  { q: 'Ilmu tentang zat?', a: 'kimia' },
  { q: 'Wujud air saat membeku?', a: 'padat' },
  { q: 'Titik didih air derajat celsius?', a: '100' },
  { q: 'Titik beku air derajat celsius?', a: '0' },

  // ===== Matematika =====
  { q: '10 + 15 = ?', a: '25' },
  { q: '100 - 47 = ?', a: '53' },
  { q: '12 x 12 = ?', a: '144' },
  { q: '144 : 12 = ?', a: '12' },
  { q: 'Akar dari 81 = ?', a: '9' },
  { q: 'Akar dari 144 = ?', a: '12' },
  { q: '5 x 8 = ?', a: '40' },
  { q: '7 x 9 = ?', a: '63' },
  { q: '9 x 9 = ?', a: '81' },
  { q: '50 : 5 = ?', a: '10' },
  { q: '25 + 75 = ?', a: '100' },
  { q: '1000 - 250 = ?', a: '750' },
  { q: 'Berapa sisi segitiga?', a: '3' },
  { q: 'Berapa sisi persegi?', a: '4' },
  { q: 'Berapa sisi segi lima?', a: '5' },
  { q: 'Berapa sisi segi enam?', a: '6' },
  { q: 'Bilangan prima terkecil?', a: '2' },
  { q: 'Pi (π) = ?', a: '3,14' },
  { q: 'Jumlah sudut segitiga derajat?', a: '180' },
  { q: 'Jumlah sudut persegi derajat?', a: '360' },

  // ===== Umum =====
  { q: 'Hewan tercepat di darat?', a: 'cheetah' },
  { q: 'Hewan terbesar di dunia?', a: 'paus biru' },
  { q: 'Hewan terbesar di darat?', a: 'gajah' },
  { q: 'Hewan tertinggi di dunia?', a: 'jerapah' },
  { q: 'Hewan paling pintar di laut?', a: 'dolphin' },
  { q: 'Raja hutan?', a: 'singa' },
  { q: 'Hewan berkantung dari Australia?', a: 'kanguru' },
  { q: 'Hewan yang bisa mengubah warna?', a: 'bunglon' },
  { q: 'Hewan yang tidur sambil berdiri?', a: 'kuda' },
  { q: 'Berapa jumlah pemain sepak bola?', a: '11' },
  { q: 'Berapa jumlah pemain basket?', a: '5' },
  { q: 'Berapa jumlah pemain voli?', a: '6' },
  { q: 'Berapa jumlah pemain bulu tangkis tunggal?', a: '1' },
  { q: 'Warna bendera Indonesia?', a: 'merah putih' },
  { q: 'Berapa warna pelangi?', a: '7' },
  { q: 'Berapa hari dalam seminggu?', a: '7' },
  { q: 'Berapa bulan dalam setahun?', a: '12' },
  { q: 'Berapa jam dalam sehari?', a: '24' },
  { q: 'Berapa menit dalam 1 jam?', a: '60' },
  { q: 'Berapa detik dalam 1 menit?', a: '60' },
  { q: 'Berapa jumlah huruf alfabet?', a: '26' },
  { q: 'Alat musik berdawai?', a: 'gitar' },
  { q: 'Alat musik dipukul?', a: 'drum' },
  { q: 'Alat musik ditiup?', a: 'terompet' },
  { q: 'Olahraga di atas es?', a: 'skating' },
  { q: 'Olahraga memakai raket?', a: 'tenis' },
  { q: 'Bahan utama kertas?', a: 'kayu' },
  { q: 'Bahan utama kaca?', a: 'pasir' },
  { q: 'Rasa buah lemon?', a: 'asam' },
  { q: 'Rasa madu?', a: 'manis' },
  { q: 'Warna darah?', a: 'merah' },
  { q: 'Warna daun?', a: 'hijau' },
  { q: 'Warna langit cerah?', a: 'biru' },
  { q: 'Sebutkan alat untuk menulis?', a: 'pulpen' },
  { q: 'Sebutkan alat untuk menghapus tulisan pensil?', a: 'penghapus' },
  { q: 'Sebutkan alat untuk mengukur panjang?', a: 'penggaris' },
  { q: 'Kendaraan di rel?', a: 'kereta' },
  { q: 'Kendaraan di laut?', a: 'kapal' },
  { q: 'Kendaraan di udara?', a: 'pesawat' },
  { q: 'Kendaraan roda dua?', a: 'motor' },
  { q: 'Kendaraan roda empat?', a: 'mobil' },
  { q: 'Ibu dari ayah kita disebut?', a: 'nenek' },
  { q: 'Anak dari kakak kita disebut?', a: 'keponakan' },
  { q: 'Saudara kembar berbeda jenis disebut?', a: 'kembar' },
  { q: 'Tempat menyimpan uang di bank?', a: 'tabungan' },
  { q: 'Alat pembayaran elektronik?', a: 'kartu' },
  { q: 'Profesi yang mengajar di sekolah?', a: 'guru' },
  { q: 'Profesi yang memadamkan api?', a: 'pemadam kebakaran' },
  { q: 'Profesi yang menerbangkan pesawat?', a: 'pilot' },
  { q: 'Profesi yang mengobati orang sakit?', a: 'dokter' },
  { q: 'Hari setelah Rabu?', a: 'kamis' },
  { q: 'Hari sebelum Senin?', a: 'minggu' },
  { q: 'Bulan setelah Desember?', a: 'januari' },
  { q: 'Bulan kemerdekaan Indonesia?', a: 'agustus' },
];

module.exports = {
  name: 'quiz',
  category: 'game',
  aliases: ['kuis', 'tquiz'],
  async execute(sock, msg, args, ctx) {
    const { from, sender, gameState, setGameTimeout, random } = ctx;
    const q = random(QUESTIONS);
    gameState[from] = { game: 'quiz', jawab: q.a, sender };
    setGameTimeout(from, async () => {
      await sock.sendMessage(from, { text: `⏰ *WAKTU HABIS!*\n\nJawaban: *${q.a}*` });
    });
    await sock.sendMessage(from, {
      text: `❓ *QUIZ* (${QUESTIONS.length} soal)\n\n${q.q}\n\n💬 *Ketik jawabanmu langsung di chat!*\n🏳️ Ketik *nyerah* untuk skip\n\n⏱️ 60 detik | +10 Point, +Rp 1000`,
    });
  },
};
