const DATA = [
  { flag: '🇮🇩', negara: 'indonesia' },
  { flag: '🇯🇵', negara: 'jepang' },
  { flag: '🇰🇷', negara: 'korea selatan' },
  { flag: '🇨🇳', negara: 'china' },
  { flag: '🇺🇸', negara: 'amerika serikat' },
  { flag: '🇬🇧', negara: 'inggris' },
  { flag: '🇫🇷', negara: 'prancis' },
  { flag: '🇩🇪', negara: 'jerman' },
  { flag: '🇮🇹', negara: 'italia' },
  { flag: '🇪🇸', negara: 'spanyol' },
  { flag: '🇵🇹', negara: 'portugal' },
  { flag: '🇳🇱', negara: 'belanda' },
  { flag: '🇧🇪', negara: 'belgia' },
  { flag: '🇨🇭', negara: 'swiss' },
  { flag: '🇸🇪', negara: 'swedia' },
  { flag: '🇳🇴', negara: 'norwegia' },
  { flag: '🇫🇮', negara: 'finlandia' },
  { flag: '🇷🇺', negara: 'rusia' },
  { flag: '🇺🇦', negara: 'ukraina' },
  { flag: '🇵🇱', negara: 'polandia' },
  { flag: '🇬🇷', negara: 'yunani' },
  { flag: '🇹🇷', negara: 'turki' },
  { flag: '🇸🇦', negara: 'arab saudi' },
  { flag: '🇦🇪', negara: 'uni emirat arab' },
  { flag: '🇪🇬', negara: 'mesir' },
  { flag: '🇿🇦', negara: 'afrika selatan' },
  { flag: '🇳🇬', negara: 'nigeria' },
  { flag: '🇰🇪', negara: 'kenya' },
  { flag: '🇮🇳', negara: 'india' },
  { flag: '🇵🇰', negara: 'pakistan' },
  { flag: '🇧🇩', negara: 'bangladesh' },
  { flag: '🇱🇰', negara: 'sri lanka' },
  { flag: '🇳🇵', negara: 'nepal' },
  { flag: '🇹🇭', negara: 'thailand' },
  { flag: '🇻🇳', negara: 'vietnam' },
  { flag: '🇲🇾', negara: 'malaysia' },
  { flag: '🇸🇬', negara: 'singapura' },
  { flag: '🇵🇭', negara: 'filipina' },
  { flag: '🇰🇭', negara: 'kamboja' },
  { flag: '🇲🇲', negara: 'myanmar' },
  { flag: '🇦🇺', negara: 'australia' },
  { flag: '🇳🇿', negara: 'selandia baru' },
  { flag: '🇨🇦', negara: 'kanada' },
  { flag: '🇧🇷', negara: 'brazil' },
  { flag: '🇦🇷', negara: 'argentina' },
  { flag: '🇲🇽', negara: 'meksiko' },
  { flag: '🇨🇱', negara: 'chile' },
  { flag: '🇨🇴', negara: 'kolombia' },
  { flag: '🇵🇪', negara: 'peru' },
  { flag: '🇮🇷', negara: 'iran' },
  { flag: '🇮🇶', negara: 'irak' },
  { flag: '🇮🇱', negara: 'israel' },
  { flag: '🇶🇦', negara: 'qatar' },
  { flag: '🇰🇼', negara: 'kuwait' },
  { flag: '🇴🇲', negara: 'oman' },
  { flag: '🇯🇴', negara: 'yordania' },
  { flag: '🇱🇧', negara: 'libanon' },
  { flag: '🇸🇾', negara: 'suriah' },
  { flag: '🇦🇹', negara: 'austria' },
  { flag: '🇩🇰', negara: 'denmark' },
  { flag: '🇮🇪', negara: 'irlandia' },
  { flag: '🇨🇿', negara: 'ceko' },
  { flag: '🇭🇺', negara: 'hungaria' },
  { flag: '🇷🇴', negara: 'rumania' },
  { flag: '🇧🇬', negara: 'bulgaria' },
  { flag: '🇭🇷', negara: 'kroasia' },
  { flag: '🇷🇸', negara: 'serbia' },
  { flag: '🇲🇦', negara: 'maroko' },
  { flag: '🇩🇿', negara: 'aljazair' },
  { flag: '🇹🇳', negara: 'tunisia' },
  { flag: '🇱🇾', negara: 'libya' },
  { flag: '🇸🇩', negara: 'sudan' },
  { flag: '🇪🇹', negara: 'ethiopia' },
  { flag: '🇬🇭', negara: 'ghana' },
  { flag: '🇹🇿', negara: 'tanzania' },
  { flag: '🇺🇬', negara: 'uganda' },
];

module.exports = {
  name: 'tebakbendera',
  category: 'game',
  aliases: ['tbbendera', 'bendera', 'flag'],
  async execute(sock, msg, args, ctx) {
    const { from, sender, gameState, setGameTimeout, random } = ctx;
    const d = random(DATA);
    gameState[from] = { game: 'tebakbendera', jawab: d.negara, sender };
    setGameTimeout(from, async () => {
      await sock.sendMessage(from, { text: `⏰ *WAKTU HABIS!*\n\nJawaban: *${d.negara}*` });
    });
    await sock.sendMessage(from, {
      text: `🏳️ *TEBAK BENDERA*\n\n${d.flag}\n\nNegara apakah bendera ini?\n\n💬 *Ketik jawabanmu langsung di chat!*\n🏳️ Ketik *nyerah* untuk skip\n\n⏱️ 60 detik | +3 Point, +Rp 700`,
    });
  },
};
