const DATA = [
  { surah: 'al-fatihah', clue: 'Surah pembuka Al-Qur\'an, 7 ayat, disebut Ummul Kitab' },
  { surah: 'al-baqarah', clue: 'Surah terpanjang, 286 ayat, berisi ayat kursi' },
  { surah: 'ali imran', clue: 'Surah ke-3, dinamai keluarga Imran' },
  { surah: 'an-nisa', clue: 'Surah ke-4, artinya "wanita", banyak bahas warisan' },
  { surah: 'al-maidah', clue: 'Surah ke-5, artinya "hidangan" ' },
  { surah: 'al-anam', clue: 'Surah ke-6, artinya "binatang ternak"' },
  { surah: 'al-araf', clue: 'Surah ke-7, artinya "tempat tertinggi"' },
  { surah: 'al-anfal', clue: 'Surah ke-8, artinya "harta rampasan perang"' },
  { surah: 'at-taubah', clue: 'Surah ke-9, satu-satunya yang tidak diawali basmalah' },
  { surah: 'yunus', clue: 'Surah ke-10, dinamai nama seorang nabi' },
  { surah: 'hud', clue: 'Surah ke-11, tentang kisah nabi kaum Ad' },
  { surah: 'yusuf', clue: 'Surah ke-12, kisah nabi yang indah, mimpinya ditakwilkan' },
  { surah: 'ar-rad', clue: 'Surah ke-13, artinya "guruh"' },
  { surah: 'ibrahim', clue: 'Surah ke-14, bapak para nabi' },
  { surah: 'al-hijr', clue: 'Surah ke-15, artinya "bukit berbatu"' },
  { surah: 'an-nahl', clue: 'Surah ke-16, artinya "lebah"' },
  { surah: 'al-isra', clue: 'Surah ke-17, tentang perjalanan malam Nabi, disebut juga Bani Israil' },
  { surah: 'al-kahf', clue: 'Surah ke-18, tentang pemuda gua, dianjurkan baca hari Jumat' },
  { surah: 'maryam', clue: 'Surah ke-19, tentang ibu Nabi Isa' },
  { surah: 'ta-ha', clue: 'Surah ke-20, dibuka dengan dua huruf' },
  { surah: 'al-anbiya', clue: 'Surah ke-21, artinya "para nabi"' },
  { surah: 'al-hajj', clue: 'Surah ke-22, tentang ibadah ke tanah suci' },
  { surah: 'al-muminun', clue: 'Surah ke-23, artinya "orang-orang beriman"' },
  { surah: 'an-nur', clue: 'Surah ke-24, artinya "cahaya"' },
  { surah: 'al-furqan', clue: 'Surah ke-25, artinya "pembeda"' },
  { surah: 'asy-syuara', clue: 'Surah ke-26, artinya "para penyair"' },
  { surah: 'an-naml', clue: 'Surah ke-27, artinya "semut"' },
  { surah: 'al-qasas', clue: 'Surah ke-28, artinya "kisah-kisah"' },
  { surah: 'al-ankabut', clue: 'Surah ke-29, artinya "laba-laba"' },
  { surah: 'ar-rum', clue: 'Surah ke-30, tentang bangsa Romawi' },
  { surah: 'luqman', clue: 'Surah ke-31, tentang nasihat seorang bijak pada anaknya' },
  { surah: 'as-sajdah', clue: 'Surah ke-32, artinya "sujud"' },
  { surah: 'al-ahzab', clue: 'Surah ke-33, artinya "golongan bersekutu"' },
  { surah: 'saba', clue: 'Surah ke-34, tentang kaum Saba' },
  { surah: 'fatir', clue: 'Surah ke-35, artinya "pencipta"' },
  { surah: 'yasin', clue: 'Surah ke-36, jantung Al-Qur\'an' },
  { surah: 'as-saffat', clue: 'Surah ke-37, artinya "barisan-barisan"' },
  { surah: 'sad', clue: 'Surah ke-38, satu huruf nama nabi' },
  { surah: 'az-zumar', clue: 'Surah ke-39, artinya "rombongan-rombongan"' },
  { surah: 'al-mumin', clue: 'Surah ke-40, artinya "orang beriman"' },
  { surah: 'fussilat', clue: 'Surah ke-41, artinya "dijelaskan"' },
  { surah: 'asy-syura', clue: 'Surah ke-42, artinya "musyawarah"' },
  { surah: 'az-zukhruf', clue: 'Surah ke-43, artinya "perhiasan"' },
  { surah: 'ad-dukhan', clue: 'Surah ke-44, artinya "kabut"' },
  { surah: 'al-jatsiyah', clue: 'Surah ke-45, artinya "yang berlutut"' },
  { surah: 'al-ahqaf', clue: 'Surah ke-46, artinya "bukit-bukit pasir"' },
  { surah: 'muhammad', clue: 'Surah ke-47, dinamai nama nabi terakhir' },
  { surah: 'al-fath', clue: 'Surah ke-48, artinya "kemenangan"' },
  { surah: 'al-hujurat', clue: 'Surah ke-49, artinya "kamar-kamar", tentang adab' },
  { surah: 'qaaf', clue: 'Surah ke-50, dibuka satu huruf arab' },
  { surah: 'adz-dzariyat', clue: 'Surah ke-51, artinya "angin yang menerbangkan"' },
  { surah: 'at-tur', clue: 'Surah ke-52, artinya "bukit" ' },
  { surah: 'an-najm', clue: 'Surah ke-53, artinya "bintang"' },
  { surah: 'al-qamar', clue: 'Surah ke-54, artinya "bulan"' },
  { surah: 'ar-rahman', clue: 'Surah ke-55, pengantin Al-Qur\'an, banyak ulangan nikmat' },
  { surah: 'al-waqiah', clue: 'Surah ke-56, tentang hari kiamat, pembuka rezeki' },
  { surah: 'al-hadid', clue: 'Surah ke-57, artinya "besi"' },
  { surah: 'al-mujadilah', clue: 'Surah ke-58, artinya "wanita yang mengajukan gugatan"' },
  { surah: 'al-hasyr', clue: 'Surah ke-59, artinya "pengusiran"' },
  { surah: 'al-mumtahanah', clue: 'Surah ke-60, artinya "wanita yang diuji"' },
  { surah: 'as-saff', clue: 'Surah ke-61, artinya "barisan"' },
  { surah: 'al-jumuah', clue: 'Surah ke-62, tentang hari Jumat' },
  { surah: 'al-munafiqun', clue: 'Surah ke-63, tentang orang munafik' },
  { surah: 'at-taghabun', clue: 'Surah ke-64, artinya "hari ditampakkan kesalahan"' },
  { surah: 'at-talaq', clue: 'Surah ke-65, tentang talak/cerai' },
  { surah: 'at-tahrim', clue: 'Surah ke-66, artinya "mengharamkan"' },
  { surah: 'al-mulk', clue: 'Surah ke-67, tentang kerajaan, penyelamat siksa kubur' },
  { surah: 'al-qalam', clue: 'Surah ke-68, artinya "pena"' },
  { surah: 'al-haqqah', clue: 'Surah ke-69, artinya "hari kiamat yang pasti"' },
  { surah: 'al-maarij', clue: 'Surah ke-70, artinya "tempat-tempat naik"' },
  { surah: 'nuh', clue: 'Surah ke-71, tentang nabi pembuat kapal' },
  { surah: 'al-jinn', clue: 'Surah ke-72, tentang makhluk gaib' },
  { surah: 'al-muzzammil', clue: 'Surah ke-73, artinya "orang yang berselimut"' },
  { surah: 'al-muddatstsir', clue: 'Surah ke-74, artinya "orang yang berkemul"' },
  { surah: 'al-qiyamah', clue: 'Surah ke-75, artinya "hari kiamat"' },
  { surah: 'al-insan', clue: 'Surah ke-76, artinya "manusia"' },
  { surah: 'al-mursalat', clue: 'Surah ke-77, artinya "malaikat yang diutus"' },
  { surah: 'an-naba', clue: 'Surah ke-78, artinya "berita besar"' },
  { surah: 'an-naziat', clue: 'Surah ke-79, artinya "malaikat pencabut nyawa"' },
  { surah: 'abasa', clue: 'Surah ke-80, artinya "bermuka masam"' },
  { surah: 'at-takwir', clue: 'Surah ke-81, artinya "menggulung"' },
  { surah: 'al-infitar', clue: 'Surah ke-82, artinya "terbelah"' },
  { surah: 'al-mutaffifin', clue: 'Surah ke-83, tentang orang curang menakar' },
  { surah: 'al-insyiqaq', clue: 'Surah ke-84, artinya "terbelah"' },
  { surah: 'al-buruj', clue: 'Surah ke-85, artinya "gugusan bintang"' },
  { surah: 'at-tariq', clue: 'Surah ke-86, artinya "bintang malam"' },
  { surah: 'al-ala', clue: 'Surah ke-87, artinya "yang paling tinggi"' },
  { surah: 'al-gasyiyah', clue: 'Surah ke-88, artinya "hari pembalasan"' },
  { surah: 'al-fajr', clue: 'Surah ke-89, artinya "fajar"' },
  { surah: 'al-balad', clue: 'Surah ke-90, artinya "negeri"' },
  { surah: 'asy-syams', clue: 'Surah ke-91, artinya "matahari"' },
  { surah: 'al-lail', clue: 'Surah ke-92, artinya "malam"' },
  { surah: 'ad-duha', clue: 'Surah ke-93, artinya "waktu duha"' },
  { surah: 'asy-syarh', clue: 'Surah ke-94, artinya "melapangkan"' },
  { surah: 'at-tin', clue: 'Surah ke-95, artinya "buah tin"' },
  { surah: 'al-alaq', clue: 'Surah ke-96, wahyu pertama, artinya "segumpal darah"' },
  { surah: 'al-qadr', clue: 'Surah ke-97, tentang malam kemuliaan' },
  { surah: 'al-bayyinah', clue: 'Surah ke-98, artinya "bukti nyata"' },
  { surah: 'az-zalzalah', clue: 'Surah ke-99, tentang gempa' },
  { surah: 'al-adiyat', clue: 'Surah ke-100, artinya "kuda perang"' },
  { surah: 'al-qariah', clue: 'Surah ke-101, artinya "hari kiamat"' },
  { surah: 'at-takasur', clue: 'Surah ke-102, tentang bermegah-megahan' },
  { surah: 'al-asr', clue: 'Surah ke-103, tentang waktu' },
  { surah: 'al-humazah', clue: 'Surah ke-104, tentang pengumpat' },
  { surah: 'al-fil', clue: 'Surah ke-105, tentang pasukan bergajah' },
  { surah: 'quraisy', clue: 'Surah ke-106, tentang suku di Mekah' },
  { surah: 'al-maun', clue: 'Surah ke-107, artinya "barang berguna"' },
  { surah: 'al-kausar', clue: 'Surah ke-108, surah terpendek, 3 ayat' },
  { surah: 'al-kafirun', clue: 'Surah ke-109, tentang orang kafir' },
  { surah: 'an-nasr', clue: 'Surah ke-110, artinya "pertolongan"' },
  { surah: 'al-lahab', clue: 'Surah ke-111, tentang Abu Lahab' },
  { surah: 'al-ikhlas', clue: 'Surah ke-112, tentang keesaan Allah' },
  { surah: 'al-falaq', clue: 'Surah ke-113, artinya "waktu subuh"' },
  { surah: 'an-nas', clue: 'Surah ke-114, surah terakhir Al-Qur\'an' },
];

module.exports = {
  name: 'tebaksurah',
  category: 'game',
  aliases: ['tbsurah', 'surah'],
  async execute(sock, msg, args, ctx) {
    const { from, sender, gameState, setGameTimeout, random } = ctx;
    const d = random(DATA);
    gameState[from] = { game: 'tebaksurah', jawab: d.surah, sender };
    setGameTimeout(from, async () => {
      await sock.sendMessage(from, { text: `⏰ *WAKTU HABIS!*\n\nJawaban: *${d.surah}*` });
    });
    await sock.sendMessage(from, {
      text: `📖 *TEBAK SURAH*\n\n${d.clue}\n\nSurah apakah ini?\n\n💬 *Ketik jawabanmu langsung di chat!*\n🏳️ Ketik *nyerah* untuk skip\n\n⏱️ 60 detik | +4 Point, +Rp 900`,
    });
  },
};
